public enum RequestTypeConstant
{
    LOGIN = 0,
    NEW_OFFER = 1,
    GET_OFFERS = 2,
    GET_GAME_DATA = 3,
    GET_CONTRACTS = 4,
    NEW_NEGOTIATION = 5,
    GET_NEGOTIATIONS = 6,
    EDIT_NEGOTIATION_COST_PER_UNIT = 7,
    NEW_PROVIDER = 8,
    GET_PROVIDERS = 9,
    REMOVE_PROVIDER = 10,
    BUY_DC = 11,
    SELL_DC = 12,
    GET_STORAGE_PRODUCTS = 13,
    NEW_PROVIDER_NEGOTIATION = 14,
    BID_FOR_AUCTION = 15,
    TERMINATE_OFFER = 16,
    NEW_MESSAGE = 17,
    GET_All_CHATS = 18
}
